### ISSUE TITLE
Find mac address of mug

### ISSUE THREAD

**Issue by mclever** [sopelj/hass-ember-mug-component#1]
Couldn't find it in the android app. How can I find the mac address?

**Comment by sopelj** [comment]
Hey, once you've paired it with your phone, you should be able to find the MAC address under your phone's Bluetooth settings. 

Simply go into your settings, Bluetooth and choose your ember mug under your devices.  The MAC address should be there. Sometimes called "device address". 

![Screenshot_20211226-093637~2.png](https://user-images.githubusercontent.com/5285941/147411797-08a53434-9189-4ff0-8f2f-49bfda52d7fa.png)

![Screenshot_20211226-093642~2.png](https://user-images.githubusercontent.com/5285941/147411800-8cf8b0dd-fa71-408b-aaed-3802e9cd32c8.png)

Also, don't forget to turn off Bluetooth on your phone or forget the mug on your phone before testing with home assistant to avoid them fighting over the mug.

**Comment by mclever** [comment]
@sopelj my Android doesn't have anything like that. I'll do some googling and see what I can see. I wonder if it was on the box that I threw away too?

**Comment by mclever** [comment]
FYI just installed a free app I found by searching for Bluetooth Mac finder in Google store. Worked perfectly!

Thanks
