### ISSUE TITLE
can't pair mug, .4 beta 5

### ISSUE THREAD

**Issue by mclever** [sopelj/hass-ember-mug-component#13]
Discovery worked the first time, even after uninstall/re-install/re-paring still getting this
Retrying setup: An error occurred updating mug: e=BleakDBusError('org.bluez.Error.Failed', 'Operation failed with ATT error: 0x0e')

**Comment by bakerboy908** [comment]
Im having the same issue, I am using an ESP32 as a Bluetooth proxy, not sure if that is a problem or not

**Comment by bakerboy908** [comment]
It appears ESPHome Bluetooth proxies cannot pair.
`This error originated from a custom integration.

Logger: custom_components.ember_mug.coordinator
Source: custom_components/ember_mug/coordinator.py:88
Integration: Ember Mug (documentation, issues)
First occurred: 23:43:33 (9 occurrences)
Last logged: 23:52:25

Pairing is not available in ESPHome.
(C3:DF:EA:CC:38:40) - C3:DF:EA:CC:38:40: Failed to connect: No backend with an available connection slot that can reach address C3:DF:EA:CC:38:40 was found
(C3:DF:EA:CC:38:40) - C3:DF:EA:CC:38:40: Failed to connect: Timeout waiting for connect response`

**Comment by sopelj** [comment]
Hi @bakerboy908, I have not tested Bluetooth proxies. I'm not certain they work. 
Are you using the latest beta of this integration and are you on the beta of home assistant 2022.11?
If not, please try the latest beta of this integration and either the home assistant 2022.11 beta or use the workaround mentioned in the other issue #10 of opening bluetoothctl to wake it.

If you have issues specific to Bluetooth proxies, please create an issue for that. I do plan on testing them, but I want the normal pairing to work cleanly first. Thanks!

**Comment by mclever** [comment]
installed 2022.11 and ran into the same snag, discover worked, but couldn't pair until I used the ssh terminal addon to run bluetoothctl and it paired right away
