### ISSUE TITLE
BleakNotFound Error

### ISSUE THREAD

**Issue by NateEaton** [sopelj/hass-ember-mug-component#17]
Having just discovered this integration and being a long-time Ember owner, I was excited at the prospect of having days about the cup available in HA.

I added the integration and when the cup showed up in autodiscovery, I added it. Per the instructions, I put the cup in pairing mode and waited. After a minute or so of the integration saying "Initializing", I got the attached error message.

Deets:
- HassOS running on rpi 4B
- BT integration enabled in HA
- not the first HACS integration I've added
- not the first BT device I've added to HA
- I had previously set up the mug on my phone and had BT turned off on the phone before trying this
- after getting this error, the integration want back to "Initializing" and I went into the terminal and ran bluetoothctl per Troubleshooting instructions; the integration just kept going back and forth between initializing and this error

Puzzled,
Nathan

![Screenshot_20221230-085124.png](https://user-images.githubusercontent.com/185155/210101923-e0d6bab7-c411-4aee-9e83-1f1e68e95a85.png)

**Comment by sopelj** [comment]
Hi! Glad you're trying it out. I'm sorry it's not working for you. 
I appreciate the info and that you tried the `bluetoothctl` workaround. Did you try putting the mug in and out of pairing mode as well? It needs to be in pairing mode to establish the initial connection. Do you have any more detailed errors in your logs? Thanks!

**Comment by NateEaton** [comment]
> Hi! Glad you're trying it out. I'm sorry it's not working for you. 
> I appreciate the info and that you tried the `bluetoothctl` workaround. Did you try putting the mug in and out of pairing mode a few times? It needs both modes at certain times, sometimes it takes a couple tries for the first one. And of course is it close to your Pi? Do you have any more detailed errors in your logs? Thanks!

I have tried it several times including with it near the pi. I set the dubug log option but only thing I see in homeassistant.log is the same message as screenshot.

I'll give it another try and turn pairing mode on and off a few times.

I've done some python work creating workers for bt-mqtt-gateway a while back and had even given Bleak a try but didn't realize it was standard on HassOS. Did they package it as part of the new Bluetooth integration capability?

**Comment by sopelj** [comment]
Oh ok. That's too bad. Thanks! Please let me know if you have any luck or further issues.

Oh very nice! Good work. Yeah, they added it to the new Home Assistant Bluetooth Integration which is really cool, and they've done great work on it. The integration itself depends on a specific version of bleak and a few other helper libraries, and each update they bump the versions.

However, the current component doesn't quite fit the use case of the Ember Mug because their components are 99% Passive BLE devices and even the few that are "active" are simply polled. Actually pairing and subscribing to a device works because bleak supports it, but sometimes doesn't behave right with other devices. 
I keep checking the changes in every Home Assistant release to see if there are new features that can make this work better. Especially with Bluetooth Proxies which currently don't allow pairing. The mug itself doesn't send any Bluetooth Advertisements like the other BLE devices do, you really need to pair and subscribe/query the attributes.

**Comment by digiblur** [comment]
Looks like the same thing here as I tried this over the holidays after receiving an Ember.  I only have bluetooth proxies here myself.

**Comment by cadwizzard** [comment]
@digiblur it's the proxies atm that will stop you. I had no issues (except with range) with the mug until I added a proxy. Then it's only errors until i move away from it and go to a directly connected (to the HA host) BT adapter

**Comment by sopelj** [comment]
Thanks @cadwizzard I'm glad it works for you without the proxies at least. Yeah, @digiblur I'm trying to make it work with the proxies, but it is not currently supported. I'm in the process of testing some things in 2023.1, but I don't know if it will be possible to support proxies unless they themselves are updated to support pairing, but you can follow progress in #15 if you'd like. In the meantime, please try without proxies if possible.

**Comment by digiblur** [comment]
@sopelj thanks for all of your efforts on this by the way. I will see if I can get an adapter loaded again but I remember it being an act of congress finding the right drivers and packages and it was flakey. I dropped it as proxies just worked. I will keep an eye on things.

**Comment by sopelj** [comment]
@digiblur Thanks! I'm just glad it can be useful. Oh, that's too bad. I didn't even know proxies worked without a base adapter. There is a list of known working adapters in the [Home assistant doc](https://www.home-assistant.io/integrations/bluetooth/#known-working-high-performance-adapters) I think most of those are directly supported in the Linux kernel and don't require any extra drivers or at least they are already installed in HassOS.

**Comment by digiblur** [comment]
> @digiblur Thanks! I'm just glad it can be useful. Oh, that's too bad. I didn't even know proxies worked without a base adapter. There is a list of known working adapters in the [Home assistant doc](https://www.home-assistant.io/integrations/bluetooth/#known-working-high-performance-adapters) I think most of those are directly supported in the Linux kernel and don't require any extra drivers or at least they are already installed in HassOS.

I'm using unRaid with the HA docker container.  No HAOS in play here, it is usually better being a little bare but not in this case.  I think the firmware files I tried before didn't work correctly with the bluez package etc, I had it kind of working but it was a manual process on reboots to remount files and such in the right order to do the bluetooth dance, then proxies came and all was well.

**Comment by smarthomeaf** [comment]
I have the same issue.  Within Range of my Home Assistance server with BlueTooth it works great.   But when Connected to Bluetooth Proxy i receive the error.

**Comment by smarthomeaf** [comment]
I have the same issue.  Within Range of my Home Assistance server with BlueTooth it works great.   But when Connected to Bluetooth Proxy i receive the error.

**Comment by NateEaton** [comment]
After installing HA core 2023.1, I reinstalled the component and tried again, this time adding the mug to app on my phone from scratch, forgetting the paring on my phone and putting the mug in pairing mode after which it was discovered and I was able to add it and see data. 

I put the mug back on charging  base in the kitchen and sat down to dinner then afterwards planned to add entities for the mug to a dashboard, test services, etc. What I noticed was that nothing had updated for an hour or so. I moved the mug back into the office (down the hall from the kitchen, where the HA hub is located) and waited a bit but still nothing. I tried putting the mug back in pairing mode for a bit but that didn't help. Finally, I restarted HA core. After that, I started getting the BleakNotFound error message as the component looped through initialization. 

One thing I noticed is that the mug, unlike many other BLE devices I have, doesn't appear to continually advertise. At least when I checked for it in the LightBlue app, it wasn't showing up unless I put it in pairing mode. After taking it out of pairing mode it would still appear for a bit but then after a while (perhaps after I put it back on charger) it was no longer showing up. 

Is that normal?

Frankly, I would be quite happy to just have polling features of this component as once I have the mug set up in the app I almost never change the color or temperature and about the only time I actually want to see data from the app is if I need to check the battery level or how close the mug contents are to the target temperature. I had considered using information from your Python Ember Mug project to see if I could add a polling-only decoder to Theengs (since I have the Theengs Gateway running on a RPI Zero W) on the kitchen end of the house but if the mug doesn't regularly advertise, I'm not sure that's feasible.

**Comment by sopelj** [comment]
> I'm using unRaid with the HA docker container. No HAOS in play here, it is usually better being a little bare but not in this case. I think the firmware files I tried before didn't work correctly with the bluez package etc, I had it kind of working but it was a manual process on reboots to remount files and such in the right order to do the bluetooth dance, then proxies came and all was well.
Oh, OK. I'm not sure about your case then, sorry. Being bare bones can be good in general, but then you have to take care of permissions, drivers and hardware pass-through so it's a bit more work. The advantage HassOS is that it is already configured, you just need to pass through the USB device. I hope you can get it working, though.

**Comment by sopelj** [comment]
> I have the same issue. Within Range of my Home Assistance server with BlueTooth it works great. But when Connected to Bluetooth Proxy i receive the error.

This is normal as Bluetooth Proxies don't currently work. Please see #15

**Comment by sopelj** [comment]
> After installing HA core 2023.1, I reinstalled the component and tried again, this time adding the mug to app on my phone from scratch, forgetting the paring on my phone and putting the mug in pairing mode after which it was discovered and I was able to add it and see data.
> 
> I put the mug back on charging base in the kitchen and sat down to dinner then afterwards planned to add entities for the mug to a dashboard, test services, etc. What I noticed was that nothing had updated for an hour or so. I moved the mug back into the office (down the hall from the kitchen, where the HA hub is located) and waited a bit but still nothing. I tried putting the mug back in pairing mode for a bit but that didn't help. Finally, I restarted HA core. After that, I started getting the BleakNotFound error message as the component looped through initialization.
> 
> One thing I noticed is that the mug, unlike many other BLE devices I have, doesn't appear to continually advertise. At least when I checked for it in the LightBlue app, it wasn't showing up unless I put it in pairing mode. After taking it out of pairing mode it would still appear for a bit but then after a while (perhaps after I put it back on charger) it was no longer showing up.
> 
> Is that normal?
> 
> Frankly, I would be quite happy to just have polling features of this component as once I have the mug set up in the app I almost never change the color or temperature and about the only time I actually want to see data from the app is if I need to check the battery level or how close the mug contents are to the target temperature. I had considered using information from your Python Ember Mug project to see if I could add a polling-only decoder to Theengs (since I have the Theengs Gateway running on a RPI Zero W) on the kitchen end of the house but if the mug doesn't regularly advertise, I'm not sure that's feasible.

Thank you very much for trying all this. So, Home Assistant did detect the mugs initially and create the entities, but then failed to update them after you got too far away (but then didn't re-connect after you returned in range)? Oh, OK. Do you have any other messages in your logs from this integration? You might need to specifically set your loggers to debugging for this intergration.

Yes, good observation. The mug does indeed not issue any Bluetooth advertisements except when in pairing mode, and when in pairing mode no data can be queried. So, in order to get data you need to put it in pairing mode, pair it, which takes it out of polling mode and then subscribes to Bluetooth notifications. This integration does that: it pairs, subscribes and polls (since not all data is sent via notifications and in case some are missed).

You can definitely try, that is of course the library that this integration uses, it actually was part of this repo before I extracted it a couples months ago for re-usability. Maybe using different hardware could help, but it will be the same code behind the scenes.

**Comment by sopelj** [comment]
This issue is old and should be resolved with the update to Home Assistant 2023.4 and release 0.6.0 of this integration. If you still have issues, please create a new issue. :)
