### ISSUE TITLE
BleakDBusError('org.bluez.Error.NotPermitted', 'Not paired')

### ISSUE THREAD

**Issue by dantrauner** [sopelj/hass-ember-mug-component#20]
Getting the following error during setup with a supported BT adapter that worked for at least one other device successfully. The adapter is a Plugable USB-BT4LE (BCM20702A0).

```
Retrying setup: An error occurred updating mug: e=BleakDBusError('org.bluez.Error.NotPermitted', 'Not paired')
```

![ember_mug](https://user-images.githubusercontent.com/1462423/212489242-42a5e8e0-f873-4ba0-a58e-a00ece155457.png)

Things I've tried (besides the normal setup instructions in the README):

- Restart Home Assistant
- Restart the host
- Enter/exit pairing mode on the mug at different times during setup
- Reinstalled the integration
- Hard reset the mug

Since I was able to pair another device and set it up fully, I have a feeling this is specific to either this integration, or some characteristic of the mug itself as a bluetooth device which makes it different from others...

**Comment by dantrauner** [comment]
Ha, I figured it out. Seems to be some kind of interference -- using an extension cable to move the dongle away from the USB ports and Pi in general allowed it to pair.

**Comment by sopelj** [comment]
Awesome! Glad you got it working and thanks for providing your solution for others too. :)
