### ISSUE TITLE
Failed to pair: org.bluez.Error.AuthenticationFailed

### ISSUE THREAD

**Issue by tayloraleach** [sopelj/hass-ember-mug-component#23]
I am trying to pair my mug and I followed all the steps. Can you elaborate on this step here from the README?

3. Home Assistant should auto-detect the mug and prompt you to configure it.
    Choose "Configure"
    And then hit "Next"

I might be misunderstanding so I was trying to connect my mug directly from the command line with `bluetoothctl pair XXXXX` but not succeeding.

Should I be able to somehow configure the connection to the mug from my HA UI?

Thanks

**Comment by sopelj** [comment]
Hi! Yes, the integration should be set up via the UI. Have you set up the Bluetooth integration in Home assistant? 

This is the basic flow:

1. Setup the Bluetooth integration in home assistant with your Bluetooth adapter
2. Install this integration via HACS
3. Restart Home Assistant 
4. Ensure your mug is close enough to your adapter and place the mode in pairing mode.
5. You should get a notification that the mug was discovered. 
6. Click on the notification and choose configure
7. You can change the name and temperature unit if you'd like and then choose.

(If you've already manually added the mug via `bluetoothctl` you will need to remove (`bluetoothctl remove YourMAC`) it in order for Home Assistant to auto discover it.

**Comment by tayloraleach** [comment]
> Hi! Yes, the integration should be set up via the UI. Have you set up the Bluetooth integration in Home assistant?
> 
> This is the basic flow:
> 
> 1. Setup the Bluetooth integration in home assistant with your Bluetooth adapter
> 2. Install this integration via HACS
> 3. Restart Home Assistant
> 4. Ensure your mug is close enough to your adapter and place the mode in pairing mode.
> 5. You should get a notification that the mug was discovered.
> 6. Click on the notification and choose configure
> 7. You can change the name and temperature unit if you'd like and then choose.
> 
> (If you've already manually added the mug via `bluetoothctl` you will need to remove (`bluetoothctl remove YourMAC`) it in order for Home Assistant to auto discover it.

Appreciate the swift reply!

Yes, I believe I did all the steps. Installed HACS, added the repo, and installed Bluetooth integration. 

When I turn the mug to pairing mode I am unsure what I should be expecting, something to pop up? (I have never used the Bluetooth integration before)

![image](https://user-images.githubusercontent.com/25046653/214753080-953bf70c-4c55-4c97-8572-2921ebb3bca5.png)

**Comment by sopelj** [comment]
Oh ok, that's good. And you're on the latest version of Home Assistant and this integration?

You should get a notification, I don't have an example at the moment, but in your screenshot, the block cut-off on the left with the blue header and outline looks like a discovered device. You should get one like that for the mug.

If you don't see it, please make sure you have removed the mug you added manually and try taking the mug out of pairing mode and back. It can be a bit finicky. 

You can also open `bluetoothctl` in another tab to see the activity and see if the mug is detected. But you don't have to interact with it, it's just for debugging.

**Comment by tayloraleach** [comment]
Ah yes, finally got it working now! I initially did not add the downloaded repo in HACS (still learning HA).

I then received the notification once the mug was in pairing mode, but was getting errors with the Bluetooth integration/paring process so I dumped the logs

`2023-01-25 19:48:04.594 ERROR (MainThread) [custom_components.ember_mug.coordinator] 
2023-01-25 19:48:04.595 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Ember Ceramic Mug' for ember_mug integration not ready yet: An error occurred updating mug: e=EOFError(); Retrying in background
2023-01-25 19:48:10.421 ERROR (MainThread) [custom_components.ember_mug.coordinator] [org.freedesktop.DBus.Error.UnknownObject] Method "ReadValue" with signature "a{sv}" on interface "org.bluez.GattCharacteristic1" doesn't exist`

So then I ssh into my HA box and ran `bluetoothctl` and it asked me to accept the mug after I type yes and everything seems to be connected. Cool!

Cheers

**Comment by sopelj** [comment]
That's awesome! I'm glad you got it working. Good job. Don't hesitate if you have any other questions/issues 😁

**Comment by tayloraleach** [comment]
Are you able to share your card yaml configuration?

I am struggling to allow the ability to set the temperature of the mug, all I can do is view the values from the default entities card.

**Comment by tayloraleach** [comment]
> > Are you able to share your card yaml configuration?
> > I am struggling to allow the ability to set the temperature of the mug, all I can do is view the values from the default entities card.
> 
> Of course! Yeah, sorry, the readme is for the development version. The current release only lets you set it via a custom service call, which isn't too intuitive, that's why I've been working on this version. I can create a beta release after work if you'd like to try it, if not you can change the readme to the tag 0.4.1 instead of `main` to see the old doc.

That would be great, thanks.

I would love to contribute to some documentation but I need a better understanding on the basic setup first haha

**Comment by sopelj** [comment]
Ok, I created `0.5.0-beta-1` which will work on Home Assistant 2023.1+, but the next beta, and the official release will only work on 2023.2+ because there are a few changes to Bluetooth in it, behind the scenes. If you want to try it, in HACS you can select this integration, choose "Redownload" and check "Show beta versions".

![screenshot-2023-01-26-17-10-30](https://user-images.githubusercontent.com/5285941/214962793-9fef7e74-ab56-4786-b2a2-43ede17a76dc.png)

That would be awesome. Contributions are always appreciated
