### ISSUE TITLE
BleakDBusError('org.bluez.Error.Failed

### ISSUE THREAD

**Issue by JuhaFIN1** [sopelj/hass-ember-mug-component#24]
Hello, just bought mug 2 and updated it to latest firmware. After this i have tried multiple times add to HA, but after HA finds it automatically, comes this error. Mug is just next to bluetooth dongle and iphone bluetooth is off ( not connected to phone same time ).

Retrying setup: An error occurred updating mug: e=BleakDBusError('org.bluez.Error.Failed', 'Operation failed with ATT error: 0x0e')

**Comment by sopelj** [comment]
Hey,thanks for the info. 
Have you tried the steps in the [Troubleshooting section](https://github.com/sopelj/hass-ember-mug-component#operation-failed-with-att-error-0x0e-or-another-connection-error) for this issue? Usually you just need to open bluetoothctl to force it to see the mug the first time, once paired it should be all good.And sometimes taking it in and out of pairing mode can help too.
If not, are you on the latest Home Assistant and version (0.4.1) of this integration?

**Comment by JuhaFIN1** [comment]
> Hey,thanks for the info. Have you tried the steps in the [Troubleshooting section](https://github.com/sopelj/hass-ember-mug-component#operation-failed-with-att-error-0x0e-or-another-connection-error) for this issue? Usually you just need to open bluetoothctl to force it to see the mug the first time, once paired it should be all good.And sometimes taking it in and out of pairing mode can help too. If not, are you on the latest Home Assistant and version (0.4.1) of this integration?

Yeah, this was issue, It was working fine after this. FIY newest beta 2023.3 dosent work anymore with mug!!

**Comment by sopelj** [comment]
@JuhaFIN1 awesome thanks! I'll close this then. 

Yes, thanks for pointing that out. I'll try and fix that tonight. It does partially work, but the changed the decimal precision again so the sensors won't load. If it's not fixed soon, feel free to open an issue about it.

**Comment by sopelj** [comment]
@JuhaFIN1 FYI 2023.3 should work if you install 0.5.1-beta-1
