### ISSUE TITLE
General Mug Use Guide?

### ISSUE THREAD

**Issue by MrKuenning** [sopelj/hass-ember-mug-component#25]
* Home Assistant Version: 2023.3
* Ember Mug Component Version: 0.5.0-beta-5

Not as much of a technical question here.  What is the proper workflow for using the mug?
As in, how to turn it off? When to charge etc.

I have had my mug for a few weeks and used it every day, and I still, fail to understand the correct way to use the mug.

I have tried putting the charger on the kitchen counter and charging it after it's washed, but I find the battery doesn't last long enough to finish my coffee at my desk.  

So I thought I would put the charger on my desk so I could charge it during and after I am done drinking.  This resulted in the mug not turning off and even the few drops of coffee at the bottom of my mug roasting and roasting until it's baked in.  Multiple times I would pick it up and hold down the power button so that the lights would go black but it would wake right back up when I set it back onto the charger.

Speaking of lights I have noticed many light patterns.

Green (My set light color) Means the mug is on?
Pulsing White: cooling?
Pulsing red: charging?

Holding the power down:
3 seconds black: Off?
5 seconds pulsing blue: pairing mode?
10 seconds blinking yellow: ??
15 seconds blinking red: factory reset?

I am sorry if I am being an idiot and missing something.  But I have had what feels like super inconsistent results using the mug.  Sometimes not heat at all, and sometimes not stop heating.

I was hoping someone could walk me through their process.

Like do you power it on before you pour in your drink?
Do you keep it on the charger while drinking?
How do you stop it from heating?   
(I noticed in the app there was a setting to stop heating, I have not found that in the HASS integration.)
When do you charge it back up?

**Comment by sopelj** [comment]
Hi, I'm not really sure what you mean. I don't believe there is a "proper" workflow. They do have a "quick start guide" that comes with the mug I believe, it's also available [on their website](https://support.ember.com/hc/en-us/articles/115002624512-Ember-Mug-Quick-Start-Guide)

I've had it for a while now, and I've never turned it "off". I usually just leave it on the charger and remove it only to use it, drink my coffee, rinse it out and the put it back on the charger. It is true that the battery doesn't last that long. About an hour or two, depending on how much it needs to heat the liquid. 

As for the lights, you're mostly correct. Green also means charged, so you might want to choose another colour to avoid confusion. A quick summary of the quick start guide is:

Lights:
- Solid White: Temperature reached
- Heating/cooling: Pulsing white
- Low battery: Slowly pulsing red
- Dead battery: solid red
- Fully charged: Solid green
- Normal: Your selected colour
- Blinking blue: Pairing Mode

Modes:
- Hold down for 4-5 seconds to turn off
- Press once when off to turn on
- Hold for 5-7 seconds to enter pairing mode (it will blink blue)
- Hold 14 seconds until light flashes red to reset. Flashing yellow is a warning that it will reset if you keep holding.


As stated above, I just leave my mug on and on the charging base turning it off, doesn't seem to really turn it off anyway, as it will wake automatically when you do basically anything. And this way it's always charged and ready for use.

No, I do not know how to trigger the "stop heating" manually. I can look into it, but for now it is not possible. The mug will automatically stop heating when it's at the correct temperature or if the battery gets too low. However, yes, if there is still "liquid" in the mug (aka it's wet) it will keep heating and can dry up coffee or sediment in the bottom, so I usually rinse and dry it out after I'm done before putting it back on the charger.

**Comment by MrKuenning** [comment]
Thank you for your helpful insight.

**Comment by sopelj** [comment]
No problem! I've added a [link to the README](https://github.com/sopelj/hass-ember-mug-component#changing-modes--button-functions) in case any others are missing the guide.
I think that's probably as much as we can do here, but feel free to issues if you have problems in future.
