### ISSUE TITLE
home-assistant is stuck

### ISSUE THREAD

**Issue by bwduncan** [sopelj/hass-ember-mug-component#26]
* Home Assistant Version (eg. 2023.2): 2023.2.3
* Ember Mug Component Version (eg. 0.5.0): 0.5.0

### Description

It's just stuck. I made a coffee and now home assistant is dead. 100% CPU on one core. pyrasite gdb stack trace below

### Logs / Errors

```
Stack for thread 1995599936
  File "/srv/homeassistant/bin/hass", line 8, in <module>
    sys.exit(main())
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/__main__.py", line 214, in main
    exit_code = runner.run(runtime_conf)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/runner.py", line 128, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1906, in _run_once
    handle._run()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/homeassistant/lib/python3.10/site-packages/dbus_fast/aio/message_reader.py", line 28, in _message_reader
    process(message)
  File "/srv/homeassistant/lib/python3.10/site-packages/dbus_fast/message_bus.py", line 853, in _process_message
    return
  File "/srv/homeassistant/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 858, in _parse_msg
    for device_path, _, on_value_changed in self._device_watchers:
  File "/srv/homeassistant/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 152, in on_value_changed
    callback(bytearray(value))
  File "/srv/homeassistant/lib/python3.10/site-packages/ember_mug/connection.py", line 345, in _notify_callback
    return

```

**Comment by bwduncan** [comment]
This might be unrelated but:

coordinator.py:163 calls `self.async_request_refresh()` from a non-async method and so it is never awaited:

```
Feb 08 16:39:40 raspberrypi hass[13542]: /home/homeassistant/data/home-assistant/custom_components/ember_mug/coordinator.py:163: RuntimeWarning: coroutine 'DataUpdateCoordinator.async_reques
t_refresh' was never awaited                                                                                                                                                                  
Feb 08 16:39:40 raspberrypi hass[13542]:   self.async_request_refresh()                                                                                                                       
Feb 08 16:39:40 raspberrypi hass[13542]: RuntimeWarning: Enable tracemalloc to get the object allocation traceback                                                                            
```

I saw a crash with "too many open files" with this error before but i think you already fixed one occurnence of this bug already, so it might not be related.

**Comment by sopelj** [comment]
Oh, yikes! That's not good! Thank you very much for the all the information. 
You are quite right that that is an async function. I changed it and I'll create beta 6. Hopefully that's all it was. Has this happened before? The line of the stacktrace is just a return in a callback, so I don't think it's a problem itself. 🤔

**Comment by bwduncan** [comment]
Haha yes you're right I think the stack trace is not entirely useful but it's the best I could do. It seems like something is looping forever without ceding control back to the event loop, but every time I ran the backtrace I just got some innocuous line like, as you say, `return`...

If that doesn't fix it I think there are other ways to debug something like this, but it requires setting up audit hooks or something ahead of time.

**Comment by sopelj** [comment]
No, it's still very much appreciated. I think you're completely right. If it was running endlessly somewhere it effectively just spit out whichever line it got tired on. I changed it to request the update in the hass event loop, so it shouldn't happen any more. 

Has this happened before? I'm just wondering if there's a way to verify if this resolves it or not. If not we can leave it open for a little bit, but I defintely don't want to release the beta if it's crashing Home Assistant.

**Comment by bwduncan** [comment]
Hey, sorry I can't really say... I've been messing around a lot with my raspberry pi lately and have had a lot of crashes related to overclocking (which wasn't a problem for years but now is), compiling python 3.10 with the old gcc in Debian 11 (have you ever seen python SIGBUS? 🤣), moving to dbus-broker and possibly some other things I was playing with. I'm also testing changes to other custom components so...

I'm happy to leave it open and keep an eye on it. Let's say if I don't see any crashes by next week we can close it. Don't worry: I drink a lot of coffee.

**Comment by sopelj** [comment]
Haha, no worries. I completely get that. No, I honestly never have. Oh that must not be fun, not a huge fan of Debian for that reason (ancient packages), hopefully it's entertaining at least. 
I've had a few crashes of Home Assistant too, that I thought it was related to my unstable VM (that I've been meaning to recreate...), but perhaps it was the same issue. 

Thanks! That would be much appreciated. I will too. I think if neither of us have issues by next week we should be OK and I'll release finalize the release. I have more I want to add, but it's never really finished so, need to release it at some point. It can always be fixed later. Haha, perfect, same ☕

**Comment by bwduncan** [comment]
`# lsof +E -aU -p $(pidof python3.10)` indicates the bug.

After running for a few hours, hass has hundreds of unix sockets open. After I remove the ember_mug component and wait 4h, it has 5 (two for logging stdout/stderr, two are an internal socketpair, and one is the dbus bluetooth connection). Unfortunately lsof can't determine the names of the unix sockets, so I can't be sure that the hundreds of open files are dbus connections.

It's possible this is a bug in hass, possibly an interaction with dbus-broker which is recommended instead of dbus-daemon, but I can't report it to them if I can't reproduce it without custom components...

**Comment by sopelj** [comment]
Yeah, it definitely can be more stable, but you always end up needing something up to date and it can get sketchy quick. But I understand.

Oh ok, well that's something.

Oh yikes! Well, that's confirmation that it's related to the integration, then. Thank you very much for your debugging. 

I looked through the issues on Bleak and there are a few mentions of similar things occurring when the Bluetooth client is reused. I have noticed it keeps re-connecting, which isn't necessarily bad, but clearly this means something isn't getting cleanup up before establishing a new connection. I didn't have time tonight, sadly, but I'll try and figure this out tomorrow night and/or this weekend.

**Comment by bwduncan** [comment]
I am certainly looking forward to Debian 12 :rofl: 

OK that makes sense. My mug is normally sitting upstairs and my raspberry pi with its tiny PCB antenna is downstairs, maybe 10m away through wall and floor, so it fails to reconnect often. That could be why I'm seeing this problem so quickly.

If there is anything I can do to help debug further please let me know.

**Comment by sopelj** [comment]
I bet! Shouldn't be too long now.

Oh ok. That makes good sense 

I did a lot of testing different things. Rewrote a part of the logic in the python library. I didn't have any issues today, so I created 0.5.0 beta 7. 
I'm hoping this does it 🤞
I saw that one other Bluetooth library uses a timeout to cleanup old sessions so it might come to that if this doesn't work.

Thanks! If you don't mind testing beta 7 that would be much appreciated. If it doesn't work I'll try with the timeouts. I'll keep testing it this week too.

**Comment by bwduncan** [comment]
Hey, thanks so much for all your hard work!

I've pulled the main branch and it's still leaky. 80 sockets open in an hour...

[home-assistant.log](https://github.com/sopelj/hass-ember-mug-component/files/10756649/home-assistant.log)

**Comment by sopelj** [comment]
Thanks! It'll be possible to get this sorted soon. It was so much easier before these Bluetooth proxies. (As cool as they are, they are quite problematic)

Damn, thanks very much for testing!
I'm testing with the disconnect timeout in main. Hopefully, it'll work.
Not sure what to try if it doesn't. 

The only other thing that seemed to work was extremely agressive, and prevented the mug from switching to new devices, thus prevents proxies from working.

**Comment by sopelj** [comment]
Oh my. Ok, I **think** I may have found the issue....
I made yet another Beta (8).

**Comment by bwduncan** [comment]
> Oh my. Ok, I **think** I may have found the issue.... I made yet another Beta (8).

Testing it now...

**Comment by bwduncan** [comment]
It looks good! I think I'm using beta 9... Is this using the timeout solution you mentioned?

```bash
(homeassistant) homeassistant@raspberrypi:~/data/home-assistant/custom_components $ while sleep 30; do echo -n "$(sudo lsof +E -aUp $(pidof python3.10) 2>/dev/null | wc -l) "; done
12 12 12 12 12 12 14 14 14 14 7 7 8 8 9 10 9 8 9 9 9 10 10 10 10 10 10 10 10 11 11 11 11 11 11 11 11 11 11 12 12 12 12 12 12 13 13 13 16 16 14 14 14 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
```

**Comment by sopelj** [comment]
Awesome! Thanks so much for testing!
0.5.0-beta-8 should be the latest.
It does include the timeout fix, that I added in beta-7, but I figured out this morning that that's not the issue... It's something so simple and infuriating. TLDR, all I had to do was remove `is True` from the conditions to check if it is connected to prevent it from constantly reconnecting....

Details:
I did some digging through `bleak` and discovered that while the base client declares the property `is_connected` and [being a boolean](https://github.com/hbldh/bleak/blob/develop/bleak/backends/client.py#L114), however, the bluezdbus client actually returns a [special class to warn about deprecations](https://github.com/hbldh/bleak/blob/develop/bleak/backends/bluezdbus/client.py#L490) which implements `__bool__`, but **is** not a boolean. So, my `self._client.is_connected is True` was always False and thus constantly reconnecting....

In the end, I don't know if I need to keep the timeout fixes, but I suppose it might be a good safeguard against leaks in future.

**Comment by sopelj** [comment]
I removed the disconnect timer, I'll do one last beta and if there are no issues over the next day or two I'll make the official release of 0.5.0.

**Comment by sopelj** [comment]
Seems to work fine. I've released 0.5.0 so we'll see how it goes. Please feel free to re-open or create a new issue if it comes back, but I think it's fixed. Thanks for your help!

**Comment by bwduncan** [comment]
Actually I was going to reply saying the same thing yesterday, but then life got in the way. I actually feel like it's much more reliable now. I get continuous graphs without gaps 😊 thanks so much!

**Comment by sopelj** [comment]
> Actually I was going to reply saying the same thing yesterday, but then life got in the way. I actually feel like it's much more reliable now. I get continuous graphs without gaps blush thanks so much!

Awesome, I'm glad! I get that, no worries. Thanks for your help. :)
