### ISSUE TITLE
No reconnecting after a restart of Home Assistant

### ISSUE THREAD

**Issue by z-master42** [sopelj/hass-ember-mug-component#31]
* Home Assistant Version (eg. 2023.2): 2023.6
* Ember Mug Component Version (eg. 0.5.0): 0.7.1

### Description

After restarting Home Assistant, the integration cannot complete the setup because it fails to re-establish a Bluetooth connection to the Mug/Cup.

### What I Did

To complete the setup, the Mug/Cup must be set to pairing mode. This is necessary each time after a restart. Before this, all entities are not available.

### Logs / Errors

```
This error was caused by a custom integration
Logger: ember_mug.mug
Source: custom_components/ember_mug/coordinator.py:62
Integration: Ember Mug (documentation, issues)
First occurred: 19:10:40 (6 occurrences)
Last logged: 19:20:10

EF:70:A4:DA:3F:B0: Ember Cup 2: Failed to connect to the mug: (EF:70:A4:DA:3F:B0) - EF:70:A4:DA:3F:B0: Failed to connect:

This error was caused by a custom integration

Logger: custom_components.ember_mug.coordinator
Source: custom_components/ember_mug/coordinator.py:72
Integration: Ember Mug (documentation, issues)
First occurred: 19:10:40 (6 occurrences)
Last logged: 19:20:10

An error occurred whilst updating the Ember Cup 2: (EF:70:A4:DA:3F:B0) - EF:70:A4:DA:3F:B0: Failed to connect:
```

**Comment by sopelj** [comment]
Oh, that's very strange. I restart relatively often, and it has not happened to me. Are you using Bluetooth Proxies or a Bluetooth dongle?

**Comment by z-master42** [comment]
No, neither a dongle nor a proxy.

**Comment by sopelj** [comment]
> No, neither a dongle nor a proxy.

What are you using then? A built-in Bluetooth card with the Bluetooth integration? On HassOS or something else?
You didn't have issues before 2023.6?

**Comment by z-master42** [comment]
I have Home Assistant (Hass OS) running on a Raspberry Pi 3 with the integrated Bluetooth chip. The behavior was already given with previous versions. Had tried so far to fix it maybe.

**Comment by rybackisback** [comment]
Hi @sopelj, I just moved to Home Assistant (Hass OS) and my ember integration does not connect anymore. See error below:

Logger: custom_components.ember_mug.coordinator
Source: custom_components/ember_mug/coordinator.py:72
Integration: Ember Mug ([documentation](https://github.com/sopelj/hass_ember_mug), [issues](https://github.com/sopelj/hass_ember_mug/issues))
First occurred: 6:42:25 AM (8 occurrences)
Last logged: 6:44:34 AM

An error occurred whilst updating the Ember Ceramic Mug: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)
An error occurred whilst updating the Ember Ceramic Mug: Not connected
An error occurred whilst updating the Ember Ceramic Mug: (xxxxxx) - xxxxxxx: Failed to connect: [org.bluez.Error.Failed] Operation already in progress

**Comment by sopelj** [comment]
Oh OK. So it's not a regression then.
This used to be a problem with proxies, but never seemed to affect dongles. Not sure why it would be a problem with built-in Bluetooth.
Do you have any other devices using the Bluetooth? 
Perhaps you can try and click "configure" on the Bluetooth Integration see if there are any options that might help? If not, you could also try manually connecting/pairing via `bluetoothctl` to see if it can help if reconnect better in future. Normally it should automatically try and reconnect unless it absolutely has to wait for a Bluetooth event.

**Comment by rybackisback** [comment]
Thanks @sopelj no other bluetooth devices. running bluetoothctl fixed it.

**Comment by sopelj** [comment]
> Thanks @sopelj no other bluetooth devices. running bluetoothctl fixed it.

Oh perfect! Does it persist through reboots now?

**Comment by sopelj** [comment]
@z-master42 Ok, thanks! I'll add that to the troubleshooting guide and then close this issue. 

For the Travel Mug 2, is it in pairing mode? We can do an issue for that. The person who helped me test the travel mug it had the first generation I think. The second should work though.

**Comment by z-master42** [comment]
Yes, I had paired in with the app, then deleted there again, reset and then turned on scan mode in bluetoothctl and put the mug in pairing mode. I will try again and if I get stuck open a new issue. This one can then be closed.

**Comment by sopelj** [comment]
@z-master42 Ok, thanks! If you can confirm it works please let me know too and I'll update the doc to list it as tested. It may have a different name than the travel mug 1. Thanks!
