### ISSUE TITLE
Stuck in pair mode

### ISSUE THREAD

**Issue by cbullard-dev** [sopelj/hass-ember-mug-component#34]
So I tried to add my ember mug, After the first attempt it said "No new Ember devices were found. Please ensure it is in pairing mode." However after saying close and then trying again it doesn't even load and only comes up with the same message.

**Comment by sopelj** [comment]
Hi! That means it was unable to detect your mug. Do you have your mug in pairing mode (ie. flashing blue) in proximity to your Bluetooth adapter or Proxy?

**Comment by cbullard-dev** [comment]
Hey there,

That is correct, I have the bug in pairing mode. The strange thing is that I can't try the searching method again, instead of searching like it did the first time around it defaults to the error message immediately

**Comment by sopelj** [comment]
That is very strange. Does your mug exit pairing mode during the process at all? Are you using the Bluetooth integration in home assistant (if so is it setup?) or Bluetooth Proxies?
Do you have any errors in your log? If not, if you could try enabling more [verbose logs](https://github.com/sopelj/hass-ember-mug-component#debugging) that would be much appreciated, thanks.

**Comment by cbullard-dev** [comment]
Never mind...

The problem was my own stupidity. I didn't know I didn't have a bluetooth adapter on the HASS server...

I have resolved the issue now. Though I don't know if it might be worth adding another error if there is no bluetooth adapter connected.
