### ISSUE TITLE
Device not found 

### ISSUE THREAD

**Issue by ryborg** [sopelj/hass-ember-mug-component#7]
`This error originated from a custom integration.`

`Logger: custom_components.ember_mug.mug`
`Source: custom_components/ember_mug/mug.py:263`
`Integration: Ember Mug (documentation)`
`First occurred: 20:14:23 (7 occurrences)`
`Last logged: 20:18:23`

`Init: Device with address E1:6E:67:C7:B0:93 was not found. on attempt 3. waiting 30sec`
`Init: Device with address E1:6E:67:C7:B0:93 was not found. on attempt 4. waiting 30sec`

This occurs right after pairing, but persists after reboot of HassOS.

**Comment by sopelj** [comment]
Oh ok. Has it every successfully connected? 
Have you tried putting it back into pairing mode after reboot? Depending on the Bluetooth adaptor and the mug firmware, sometimes it can only be detected in pairing mode after a reboot.

**Comment by ryborg** [comment]
It connected only at pairing stage, and the entities were added but never
updated. Unavailable since the start. The mug also stays in pairing mode
even though the integration sets up.

**Comment by sopelj** [comment]
Ok, that's weird. I know this isn't intuitive, not a permanent fix, but if you have the Terminal addon for home assistant or SSH access. Can you try:
```bash
bluetoothctl
# And then in the bluetooth shell
power off
# wait until it says powered off
power on 
# replace mug-mac-address with you address. Tab autocomplete should work.
bluetoothctl connect mug-mac-address
```
I didn't have to do this before, but from time to time, I have had to do it after a reboot. This seems to work everytime for me.

I've been trying to find a new one, but I only have two. I believe it needs to support Bluetooth 4.2, but it's sometimes they say 4.0 and it works too. Bluetooth 5.0 would be nice, but sadly I haven't found any that are well supported by Linux. The best supported ones seem to be the builtin wifi-bluetooth adaptors.

**Comment by sopelj** [comment]
@ryborg Did you have any luck with that?
I know it shouldn't be necessary, but it always seems to work.

**Comment by jschulman** [comment]
I’m having the same issue. I tried your approach and oddly immediately paired just by loading Bluetoothctl.

**Comment by jschulman** [comment]
I’m running the TP-Link UB500 5.0 adapter.

**Comment by ryborg** [comment]
Sorry, I didn't. Gave up. I might try again with a different device.

**Comment by sopelj** [comment]
@jschulman Ok, thank you! I don't know why it's needed, but I'll see if there's something I can do in the code, if not I'll document it. Once it's paired, it seems to persist through restarts, though. So it's a one time workaround.
That's good to know 5.0 adapters work too, thanks. :)

**Comment by ryborg** [comment]
@sopelj 
all working now with a new TP-Link BT 5.0 adapter.

**Comment by sopelj** [comment]
@ryborg Thanks!
