### ISSUE TITLE
Requirements for ember_mug not found: ['bleak==0.14.1']

### ISSUE THREAD

**Issue by mclever** [sopelj/hass-ember-mug-component#8]
Figured I'd try this integration again to see if it worked with the new Bluetooth integration on HA 2022.8 and it no longer starts. You get this error
Setup failed for custom integration ember_mug: Requirements for ember_mug not found: ['bleak==0.14.1'].

**Comment by sopelj** [comment]
Hi, yeah, you should always read the changes in Home Assistant before upgrading.
HA 2022.8 added a [new Bluetooth integration](https://www.home-assistant.io/blog/2022/08/03/release-20228/#first-class-bluetooth-support). Installing bleak seems to conflict with their install of it. I will look into migrating this to their new version if possible, but it only just came out this morning, so I haven't had time yet. In the meantime if you'd like to use it, you'll need to use HA 2022.7. I'll update this ticket with progress as soon as I can.

**Comment by sopelj** [comment]
Hey, I made some minimal fixes so it can work again in Home Assistant 2022.8+
However, it will not work if the new Bluetooth Integration is also configured. I added a note in the readme. 
So, please try the version 0.3.0 and see if it works for you.

Long term however, I will probably have to rewrite this integration to use the new one. But it will take some time.
